<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!--setting material properties which will be used later-->
<xacro:include filename="inertia.xacro"/>
<!-- Import the wheel macro -->
<xacro:include filename="$(find my_robot)/robot_urdf_description/wheel_macro.xacro"/>

<!-- Define properties -->
<xacro:property name="x_dimension" value="0.3"/> 
<xacro:property name="y_dimension" value="0.3"/>
<xacro:property name="z_dimension" value="0.15"/>

<xacro:property name="wheel_length" value="0.04"/>
<xacro:property name="wheel_radius" value="0.05"/>
<xacro:property name="wheel_mass" value="0.1"/>
<xacro:property name="chassis_mass" value="0.5"/>

<!--constants-->
<xacro:property name="PI" value="3.14159"/>

<!-- setting material colors-->
<material name="White">
    <color rgba="1 1 1 1"/>
</material>
<material name="Orange">
    <color rgba="1 0.3 0.1 1"/>
</material>
<material name="Blue">
    <color rgba="0.2 0.2 1 1"/>
</material> 
<material name="Black">
    <color rgba="0 0 0 1"/>
</material>
<material name="Brown">
    <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
</material>
<material name="Red">
    <color rgba="0.96 0.26 0.21 1.0"/>
</material>

<!--setting up the base link-->
<link name="base_link">
</link>

<!-- adding base foot print link for simultanuous localization and mapping-->
<link name="base_footprint">
</link>

<joint name ="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<!--################################# robot chassis link ###############################################-->
<link name="chassis_link">
    <visual>
        <origin xyz="${x_dimension/2} 0 ${z_dimension/2}"/> <!-- this is relative to chassis link-->
        <geometry>
            <box size="${x_dimension} ${y_dimension} ${z_dimension}"/>
        </geometry>
        <material name="White"/>
    </visual>
    <collision>
        <origin xyz="${x_dimension/2} 0 ${z_dimension/2}"/>
        <geometry>
            <box size="${x_dimension} ${y_dimension} ${z_dimension}"/>
        </geometry>
    </collision>
    <xacro:chassis_inertia mass="${chassis_mass}" x="${x_dimension}" y="${y_dimension}" z="${z_dimension}">
        <origin xyz="${x_dimension/2} 0 ${z_dimension/2}" rpy="0 0 0"/>
    </xacro:chassis_inertia>
</link>
<joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="-0.1 0 0"/> <!-- this has be changed to wheel x and z offset after measurement-->
</joint>
 <!--adding gazebo reference for displaying the exact color of the robot-->
<gazebo reference="chassis_link">
    <material>Gazebo/White</material>
</gazebo>
<!--################################################################################################-->



<!-- Use the macro for left and right wheels -->
<xacro:wheel_link 
    wheel_name="left_wheel" 
    wheel_radius ="${wheel_radius}" 
    wheel_length ="${wheel_length}" 
    wheel_mass="${wheel_mass}" 
    y_offset="${y_dimension/2 + wheel_radius/2}" 
    axis_direction="-${PI/2}"
    axis_of_rotation = "1" /> <!-- Indicates rotation of the wheels along the Z axis--> 

<xacro:wheel_link 
    wheel_name="right_wheel" 
    wheel_radius="${wheel_radius}" 
    wheel_length="${wheel_length}" 
    wheel_mass="${wheel_mass}" 
    y_offset="-${y_dimension/2 + wheel_radius/2}" 
    axis_direction="${PI/2}"
    axis_of_rotation = "-1" /> <!-- Indicates rotation of the wheels along the Z axis-->

<!-- caster wheel link-->
<link name="castor_wheel">
    <visual>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
        <material name="Black"/>
    </visual>   
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
    </collision> 
    <xacro:inertia_of_sphere mass="${wheel_mass}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertia_of_sphere>
</link>

<gazebo reference="castor_wheel">
    <material>Gazebo/Black</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
</gazebo>

<joint name="castor_wheel_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="castor_wheel"/>
    <origin xyz="0.24 0 0"/>
</joint>

</robot>


